// Code generated by "goconfig -field StdoutConsumer func(Token)|StderrConsumer func(Token)|Delim byte|CaptureStdout bool|CaptureStderr bool -option -output exec_config_generated.go -configOption Option"; DO NOT EDIT.

package execx

type ConfigItem[T any] struct {
	modified     bool
	value        T
	defaultValue T
}

func (s *ConfigItem[T]) Set(value T) {
	s.modified = true
	s.value = value
}
func (s *ConfigItem[T]) Get() T {
	if s.modified {
		return s.value
	}
	return s.defaultValue
}
func (s *ConfigItem[T]) Default() T {
	return s.defaultValue
}
func (s *ConfigItem[T]) IsModified() bool {
	return s.modified
}
func NewConfigItem[T any](defaultValue T) *ConfigItem[T] {
	return &ConfigItem[T]{
		defaultValue: defaultValue,
	}
}

type Config struct {
	StdoutConsumer *ConfigItem[func(Token)]
	StderrConsumer *ConfigItem[func(Token)]
	Delim          *ConfigItem[byte]
	CaptureStdout  *ConfigItem[bool]
	CaptureStderr  *ConfigItem[bool]
}
type ConfigBuilder struct {
	stdoutConsumer func(Token)
	stderrConsumer func(Token)
	delim          byte
	captureStdout  bool
	captureStderr  bool
}

func (s *ConfigBuilder) StdoutConsumer(v func(Token)) *ConfigBuilder {
	s.stdoutConsumer = v
	return s
}
func (s *ConfigBuilder) StderrConsumer(v func(Token)) *ConfigBuilder {
	s.stderrConsumer = v
	return s
}
func (s *ConfigBuilder) Delim(v byte) *ConfigBuilder {
	s.delim = v
	return s
}
func (s *ConfigBuilder) CaptureStdout(v bool) *ConfigBuilder {
	s.captureStdout = v
	return s
}
func (s *ConfigBuilder) CaptureStderr(v bool) *ConfigBuilder {
	s.captureStderr = v
	return s
}
func (s *ConfigBuilder) Build() *Config {
	return &Config{
		StdoutConsumer: NewConfigItem(s.stdoutConsumer),
		StderrConsumer: NewConfigItem(s.stderrConsumer),
		Delim:          NewConfigItem(s.delim),
		CaptureStdout:  NewConfigItem(s.captureStdout),
		CaptureStderr:  NewConfigItem(s.captureStderr),
	}
}

func NewConfigBuilder() *ConfigBuilder { return &ConfigBuilder{} }
func (s *Config) Apply(opt ...Option) {
	for _, x := range opt {
		x(s)
	}
}

type Option func(*Config)

func WithStdoutConsumer(v func(Token)) Option {
	return func(c *Config) {
		c.StdoutConsumer.Set(v)
	}
}
func WithStderrConsumer(v func(Token)) Option {
	return func(c *Config) {
		c.StderrConsumer.Set(v)
	}
}
func WithDelim(v byte) Option {
	return func(c *Config) {
		c.Delim.Set(v)
	}
}
func WithCaptureStdout(v bool) Option {
	return func(c *Config) {
		c.CaptureStdout.Set(v)
	}
}
func WithCaptureStderr(v bool) Option {
	return func(c *Config) {
		c.CaptureStderr.Set(v)
	}
}
