name: CI

permissions: {}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    timeout-minutes: 5
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Setup Go
        uses: actions/setup-go@v6.0.0
        with:
          go-version-file: "go.mod"
          cache-dependency-path: go.sum
      - name: Display Go version
        run: go version
      - name: Test
        run: make test
      - name: Lint
        run: make vet
      - name: Vuln
        run: make vuln
